/* Shutter — all the content lives here, so it can be checked and edited
   without touching the app. cam: 'r8' | '5d2' | 'both'. */

const CAMERAS = {
  r8: {
    name: 'EOS R8',
    short: 'R8',
    specs: [
      ['Sensor', '24.2 MP full frame, DIGIC X'],
      ['ISO', '100–102,400 (expands to 50–204,800)'],
      ['Autofocus', 'Dual Pixel CMOS AF II, eye/face/animal/vehicle detection'],
      ['Stabilisation', 'None in body — use IS lenses or faster shutter'],
      ['Shutter', 'Electronic 1st curtain to 1/4000, electronic to 1/16000'],
      ['Burst', '6 fps (1st curtain), 40 fps (electronic)'],
      ['Flash sync', '1/200 s'],
      ['Video', '4K 60p uncropped (from 6K), FHD 180p, 10‑bit C‑Log3 / HDR PQ'],
      ['Card', '1 × SD UHS‑II'],
      ['Battery', 'LP‑E17 — small, carry spares; USB‑C charging'],
      ['Mount', 'RF (EF/EF‑S lenses via EF‑EOS R adapter)']
    ]
  },
  '5d2': {
    name: 'EOS 5D Mark II',
    short: '5D II',
    specs: [
      ['Sensor', '21.1 MP full frame, DIGIC 4'],
      ['ISO', '100–6,400 (expands to 50, 12,800, 25,600)'],
      ['Autofocus', '9 points + 6 invisible assist points; only the centre is cross‑type'],
      ['Stabilisation', 'None in body'],
      ['Shutter', 'Mechanical, 30 s – 1/8000'],
      ['Burst', '3.9 fps'],
      ['Flash sync', '1/200 s'],
      ['Video', '1080p 30 (24/25p with firmware 2.0.3+), manual focus only'],
      ['Card', '1 × CompactFlash (UDMA)'],
      ['Battery', 'LP‑E6 / LP‑E6N — around 850 shots'],
      ['Mount', 'EF (RF lenses will not fit)']
    ]
  }
};

const CATEGORIES = [
  { id: 'setup',  label: 'Setup',        icon: '⚙️' },
  { id: 'focus',  label: 'Autofocus',    icon: '🎯' },
  { id: 'expo',   label: 'Exposure',     icon: '☀️' },
  { id: 'low',    label: 'Low light',    icon: '🌙' },
  { id: 'flash',  label: 'Flash',        icon: '⚡' },
  { id: 'event',  label: 'Events',       icon: '🥂' },
  { id: 'video',  label: 'Video',        icon: '🎬' },
  { id: 'kit',    label: 'Cards & power',icon: '🔋' },
  { id: 'pair',   label: 'Two bodies',   icon: '📷' },
  { id: 'lens',   label: 'My lenses',    icon: '🔭' }
];

const TIPS = [
  /* ---------------------------------------------------------------- R8 */
  { id: 'r8-bbf', cam: 'r8', cat: 'focus', title: 'Set up back‑button focus',
    body: 'Separating focus from the shutter lets you lock focus once and shoot a sequence without the camera hunting again, and keeps Servo tracking on your thumb.',
    steps: ['Menu → Customise buttons (orange Custom Functions tab).',
            'Shutter button: set to <b>Metering start</b>.',
            'AF‑ON button: set to <b>Metering and AF start</b>.',
            'Leave AF operation on Servo — hold the thumb to track, release to lock.'] },
  { id: 'r8-detect', cam: 'r8', cat: 'focus', title: 'Let subject detection do the work',
    body: 'The R8 inherits the R6 II’s detection. Set <b>Subject to detect</b> to People (or Auto), <b>Eye detection</b> to Auto, and AF area to Whole area. In Servo it will find and follow an eye anywhere in the frame — at a reception that’s the difference between a sharp candid and a missed one.',
    steps: ['AF menu → Subject to detect: People / Animals / Vehicles / Auto.',
            'Eye detection: Auto.',
            'AF area: Whole area AF (or Flexible zone to stop it jumping to the wrong face).',
            'Tap a face on the screen or use the AF‑point button to pick a different person.'] },
  { id: 'r8-noibis', cam: 'r8', cat: 'expo', title: 'No IBIS — mind your shutter speed',
    body: 'Unlike most R bodies, the R8 has no in‑body stabilisation. Handheld, aim for at least <b>1/(2 × focal length)</b> for sharp people shots — 1/100 at 50 mm, 1/200 at 85 mm — unless the lens has IS. The Tools tab has a calculator.' },
  { id: 'r8-efcs', cam: 'r8', cat: 'setup', title: 'Know its two shutter modes',
    body: 'The R8 has no fully mechanical shutter. <b>Electronic 1st‑curtain</b> is the everyday mode and the one you need for flash. <b>Electronic</b> is silent and fast but fails in three situations: flash won’t fire, LED/fluorescent lighting can produce banding, and fast motion (golf swings, panning) can skew.',
    steps: ['Shooting menu → Shutter mode.',
            'Events with flash or LED stage lighting: Elec. 1st‑curtain.',
            'Quiet ceremony in daylight/window light: Electronic.'] },
  { id: 'r8-bokeh', cam: 'r8', cat: 'expo', title: 'Chopped bokeh at fast shutter speeds',
    body: 'At 1/2000 and faster with a wide aperture, electronic 1st‑curtain can clip out‑of‑focus highlights into half‑moons and slightly underexpose one edge. For f/1.2–f/2 portraits in bright sun, either switch to full electronic (if nothing is moving fast and there’s no flash) or put an ND filter on and stay below 1/2000.' },
  { id: 'r8-expsim', cam: 'r8', cat: 'flash', title: 'Turn off exposure simulation for flash',
    body: 'In a dark room at ISO 100, 1/200, f/8 for studio strobes, the viewfinder shows the ambient exposure — black. Switch <b>Exposure simulation</b> to Disable (or the DOF‑preview option) so the EVF brightens up for framing, then turn it back on afterwards.' },
  { id: 'r8-autoiso', cam: 'r8', cat: 'expo', title: 'Manual + Auto ISO + a minimum shutter',
    body: 'For run‑and‑gun events set M, pick the aperture and shutter you want, and leave ISO on Auto. Exposure compensation still works in M with Auto ISO. In Av mode, set <b>ISO speed settings → Min. shutter spd.</b> so Auto ISO raises the ISO before the shutter drops below what the R8 can hold steady.' },
  { id: 'r8-preshoot', cam: 'r8', cat: 'event', title: 'RAW burst with pre‑shooting',
    body: 'RAW burst mode shoots 30 fps and, with pre‑shooting on, keeps the half‑second <i>before</i> you fully pressed. Perfect for confetti, the kiss, the bouquet toss or a cake cut. It uses the electronic shutter, so no flash, and it saves a single roll file you extract frames from in camera or in Canon DPP.' },
  { id: 'r8-silent', cam: 'r8', cat: 'event', title: 'Silent shooting during ceremonies',
    body: 'Electronic shutter is completely silent — ideal for vows, speeches and prayers. Check the first frame at 100% for banding if the room has LED lights; if you see stripes, go back to 1st‑curtain and keep your shutter at 1/50 or 1/100 (a multiple of the mains flicker), or turn on <b>Anti‑flicker shooting</b>.' },
  { id: 'r8-battery', cam: 'r8', cat: 'kit', title: 'The battery is the R8’s weak spot',
    body: 'The LP‑E17 is small: plan on a few hundred shots per battery with the EVF. For an event carry at least three, set Display performance to Power saving, lower Auto power off, and switch off Bluetooth/Wi‑Fi if you aren’t using Camera Connect. It charges in camera over USB‑C from a PD power bank between sets.' },
  { id: 'r8-card', cam: 'r8', cat: 'kit', title: 'One card slot — protect paid work',
    body: 'There’s no backup slot. Use a good UHS‑II card (V60 or V90), format it in the camera at the start of every job, never delete in camera, and offload during breaks at long events. Spread a big day over two or three cards so one failure can’t take the whole wedding.' },
  { id: 'r8-adapter', cam: 'r8', cat: 'pair', title: 'EF lenses on the R8',
    body: 'With Canon’s EF‑EOS R adapter every EF lens works with full autofocus, eye detection and lens IS — often focusing better than it did on the 5D II. EF‑S lenses also fit and the R8 crops to 1.6× automatically. RF lenses can’t go the other way onto the 5D II.' },
  { id: 'r8-qmenu', cam: 'r8', cat: 'setup', title: 'Build a My Menu and Quick menu',
    body: 'Put what you change on every job — Shutter mode, Subject to detect, Exposure simulation, Format card — into a My Menu tab. Then customise the Q menu so the rest is one press away. Fewer menu dives means fewer missed moments.' },
  { id: 'r8-video', cam: 'r8', cat: 'video', title: '4K without a crop',
    body: '4K 60p and 30p use the full sensor width, oversampled from 6K, so your wide lenses stay wide. For straight‑to‑client video use a normal picture style; use C‑Log3 only if you’ll colour grade (base ISO goes up to 800). Long 4K 60p takes can heat the body — for a 40‑minute speech, 4K 30p or 1080p is safer.' },
  { id: 'r8-dis', cam: 'r8', cat: 'video', title: 'Handheld video: Movie digital IS',
    body: 'With no IBIS, handheld footage is shaky unless the lens has IS. Movie digital IS (Enable or Enhanced) steadies it with a slight crop, and pairs with lens IS when the lens has it. For walking shots a gimbal is still better.' },
  { id: 'r8-focusbkt', cam: 'r8', cat: 'expo', title: 'Focus bracketing for product shots',
    body: 'On a tripod, <b>Focus bracketing</b> steps focus from near to far and can merge the result in camera. Great for machine parts and small products where even f/11 won’t get it all sharp. Use f/5.6–f/8 for the sharpest individual frames and around 20–40 shots.' },
  { id: 'r8-tether', cam: 'r8', cat: 'event', title: 'Tethering and the photo booth',
    body: 'The R8 tethers over USB‑C to EOS Utility or booth software, and a USB‑PD supply (or the DR‑E17 coupler) keeps it running all night. Turn Auto power off to Disable, use continuous lighting or a flash in 1st‑curtain mode, and lock focus with a fixed zone so every guest is sharp.' },
  { id: 'r8-zebra', cam: 'r8', cat: 'expo', title: 'Trust the EVF histogram, not the brightness',
    body: 'Screen brightness lies in a dark venue. Press INFO until you get the histogram in the viewfinder and turn on Highlight alert for playback. For white dresses, keep the right edge of the histogram just short of the wall.' },

  /* --------------------------------------------------------------- 5D II */
  { id: 'm2-centre', cam: '5d2', cat: 'focus', title: 'Trust the centre point',
    body: 'Only the centre AF point is cross‑type (and extra‑sensitive with f/2.8 or faster lenses). In low light, use the centre point, and let the 6 invisible assist points help in AI Servo. The outer points are fine in good light with contrasty subjects.' },
  { id: 'm2-recompose', cam: '5d2', cat: 'focus', title: 'Focus‑and‑recompose has a limit',
    body: 'Focusing with the centre point and swinging the camera moves your plane of focus. At f/1.4–f/2 and close distances an eye can go soft. Pick the outer point nearest the eye instead, or stop down to f/2.8 when you have to recompose.' },
  { id: 'm2-afma', cam: '5d2', cat: 'focus', title: 'Micro‑adjust every fast lens',
    body: 'If a lens front‑ or back‑focuses, <b>AF Microadjustment</b> in the Custom Functions fixes it per lens. Test on a tripod at your usual working distance, wide open, with a target at 45°; adjust in steps of a few points until the focus lands dead on. The R8 doesn’t need this — it focuses on the sensor.' },
  { id: 'm2-bbf', cam: '5d2', cat: 'focus', title: 'Back‑button focus on the 5D II',
    body: 'Custom Functions group IV → <b>Shutter button/AF‑ON button</b>. Choose the option where the shutter meters and AF‑ON starts AF. Same habit as the R8, so both bodies handle alike.' },
  { id: 'm2-iso', cam: '5d2', cat: 'low', title: 'Where the ISO ceiling really is',
    body: 'ISO 1600 is clean, 3200 is very usable if exposed properly, and 6400 is for emergencies. H1/H2 are muddy. The 5D II hates being underexposed: brightening shadows later brings out banding. Expose a little bright (to the right) rather than dark.' },
  { id: 'm2-autoiso', cam: '5d2', cat: 'expo', title: 'Auto ISO in M is stuck at 400',
    body: 'On the 5D II, Auto ISO in Manual mode just sets ISO 400. In M, set the ISO yourself. In Av/Tv, Auto ISO does work (it floats 100–3200).' },
  { id: 'm2-htp', cam: '5d2', cat: 'expo', title: 'Highlight Tone Priority for white dresses',
    body: 'HTP (Custom Functions group II) keeps about one extra stop of highlight detail — useful for bright white fabric and skies. Its trade‑offs: ISO starts at 200 and shadows get a touch noisier. Turn Auto Lighting Optimizer off if you shoot RAW; it only affects JPEGs and makes previews inconsistent.' },
  { id: 'm2-fps', cam: '5d2', cat: 'event', title: 'Anticipate — 3.9 fps won’t save you',
    body: 'Spraying won’t catch peak action at 3.9 fps. Watch the moment build and press just before it: the kiss, the laugh, the toss. For fast action hand the job to the R8.' },
  { id: 'm2-lv', cam: '5d2', cat: 'focus', title: 'Live View for critical manual focus',
    body: 'On a tripod, use Live View and magnify 5× then 10× to nail focus for products, landscapes and night sky. Live View AF is slow contrast detect, so manual focus is usually faster. For long exposures add the 2‑second timer or mirror lockup.' },
  { id: 'm2-video', cam: '5d2', cat: 'video', title: 'Shooting video on the 5D II',
    body: 'Update to the latest firmware (2.1.2) for 24/25p, manual exposure in movies and manual audio levels. There’s no continuous AF, so focus manually. Each clip stops at 4 GB (about 12 minutes). Fine repeating patterns (brick, fabric) can shimmer with moiré; step back or soften focus slightly.' },
  { id: 'm2-audio', cam: '5d2', cat: 'video', title: 'Fix the audio hiss',
    body: 'Auto gain on the 5D II is noisy. Set <b>Sound recording: Manual</b>, keep peaks around −12 dB, and use an external mic — or better, record audio separately and sync in the edit.' },
  { id: 'm2-cf', cam: '5d2', cat: 'kit', title: 'Look after the CF slot',
    body: 'CompactFlash uses pins inside the slot. Insert cards straight and gently, never force one, and keep a card reader for CF in your bag. Use UDMA cards; the camera writes around 30–40 MB/s at most, so there’s no point paying for the fastest cards.' },
  { id: 'm2-custom', cam: '5d2', cat: 'setup', title: 'Use C1, C2 and C3',
    body: 'Set up a complete look, then Menu → Camera user setting → Register to save it to the dial. For example: C1 = flash reception (M, 1/60, f/4, ISO 1600, Servo); C2 = outdoor portraits (Av, f/2.8, One Shot); C3 = tripod/landscape (M, ISO 100, 2‑s timer).' },
  { id: 'm2-spot', cam: '5d2', cat: 'expo', title: 'Spot metering is centre only',
    body: 'Spot metering (3.5%) reads the centre of the frame only, not the active AF point. For a stage‑lit speaker, meter on the face in the centre, lock with *, then recompose — or go Manual and check the histogram.' },
  { id: 'm2-lcd', cam: '5d2', cat: 'expo', title: 'Don’t judge exposure on the back screen',
    body: 'The screen looks bright in a dark room and dull outdoors. Switch playback to show the RGB histogram and highlight alert (blinkies) and judge by those.' },
  { id: 'm2-ml', cam: '5d2', cat: 'setup', title: 'Magic Lantern (optional, at your own risk)',
    body: 'Magic Lantern is free, unofficial add‑on software that runs from the memory card on firmware 2.1.2. It adds focus peaking, zebras, audio meters, an intervalometer and more. It’s widely used on the 5D II but isn’t supported by Canon — try it on a spare card first, never on a paid job.' },
  { id: 'm2-weather', cam: '5d2', cat: 'kit', title: 'Weather resistance is modest',
    body: 'The 5D II has some sealing but far less than later bodies. In rain use a rain cover or a plastic bag and rubber band, and dry it off before swapping lenses.' },


  /* ------------------------------------------------------------ LENSES */
  { id: 'l-50l-shift', cam: 'both', cat: 'lens', title: 'EF 50mm f/1.2L: beware focus shift',
    body: 'This lens is known for <b>focus shift</b>: stopped down to about f/2–f/4 at close range, the sharpest point moves slightly behind where it focused. Wide open (f/1.2–f/1.4) and at f/5.6+ it isn’t a problem. On the 5D II, AF Microadjustment can only be tuned for one aperture, so tune it for the one you use most. On either body, check the first frames at 100% whenever you shoot it at f/2–f/4 up close.' },
  { id: 'l-50l-use', cam: 'both', cat: 'lens', title: 'EF 50mm f/1.2L: getting the look',
    body: 'Wide open it’s soft and glowing with heavy vignetting, which is lovely for portraits and low light but not for groups. It gets properly sharp across the frame from about f/2.8. Focus is accurate but not fast (lots of heavy glass to move), so use it for posed and slow moments, not the dance floor rush. It takes 72 mm filters and is weather‑sealed once a filter is on.',
    steps: ['f/1.2–f/1.6: single portraits, detail shots, candlelit rooms.',
            'f/2.8–f/4: couples and small groups where both faces must be sharp.',
            'On the R8 use eye detection: the depth of field at f/1.2 is a few centimetres.'] },
  { id: 'l-85', cam: 'both', cat: 'lens', title: 'EF 85mm f/1.8: your candid lens',
    body: 'Fast, quiet ring‑USM focus that keeps up even on the 5D II. It’s the best lens you own for speeches, reactions and head‑and‑shoulders portraits. Its one weakness is <b>purple/green fringing</b> on backlit edges wide open; stop to f/2.2–f/2.8 or fix it with “Remove chromatic aberration” plus the fringe sliders in Lightroom. Minimum focus is 0.85 m. It takes 58 mm filters.' },
  { id: 'l-85-shutter', cam: 'both', cat: 'lens', title: '85 mm without stabilisation',
    body: 'Neither body nor the 85 has stabilisation, so keep at least 1/160–1/200 handheld for people. Indoors that means ISO 1600–6400 at f/1.8. That’s easy on the R8 and pushing it on the 5D II, so the 85 usually lives on the R8 in dark venues.' },
  { id: 'l-rf50', cam: 'r8', cat: 'lens', title: 'RF 50mm f/1.8 STM: the tiny kit',
    body: 'R8 + RF 50 f/1.8 is a jacket‑pocket full‑frame setup, good for scouting, travel and discreet candids. It focuses down to 30 cm, so it doubles as a detail/rings/food lens. Wide open it’s a little soft with some vignetting, and from f/2.8 it’s sharp. Its STM motor is slower than the 85 but smooth for video.' },
  { id: 'l-rf50-ring', cam: 'r8', cat: 'lens', title: 'Put the RF 50’s ring to work',
    body: 'The single ring on the RF 50 can be manual focus <i>or</i> a control ring. Flip the lens switch to CONTROL, then assign the ring to <b>exposure compensation</b> or <b>ISO</b> in Customise dials. That gives the R8 the third dial it’s missing. Switch back to FOCUS for manual focus.' },
  { id: 'l-two-50s', cam: 'r8', cat: 'lens', title: 'Two 50s on the R8 — which one?',
    body: 'Both mount on the R8 (the EF one through the adapter). Reach for the <b>EF 50 f/1.2L</b> when you want the look: shallow depth, glow and low light. Reach for the <b>RF 50 f/1.8</b> when you want small, light, close focus and snappy eye‑AF, or when rain is coming and you’d rather risk the cheap lens.' },
  { id: 'l-kit', cam: 'both', cat: 'lens', title: 'Two‑body lens pairings',
    body: 'For events, a good default is <b>R8 + 85 f/1.8</b> for candids and speeches (eye‑AF, clean high ISO), and <b>5D II + 50 f/1.2L</b> with flash for people and details. For a slow portrait session, swap: the R8’s eye‑AF makes the 50 f/1.2L far more reliable wide open than the 5D II’s centre point.' },
  { id: 'l-adapter', cam: 'r8', cat: 'lens', title: 'Adapter habits',
    body: 'Leave the EF‑EOS R adapter on one EF lens (the 50L or the 85) so a swap is lens + adapter in one move and the R8’s sensor is exposed for less time. Keep the adapter’s rear cap in your bag, and when the R8 has the RF 50 on, put the adapter on the other EF lens.' },

  /* ------------------------------------------------------------- BOTH */
  { id: 'b-raw', cam: 'both', cat: 'setup', title: 'Shoot RAW (and why)',
    body: 'RAW keeps around 2 extra stops of recoverable highlight and shadow and lets you fix white balance afterwards. Mixed venue lighting makes that essential. The R8 also offers C‑RAW — about 40% smaller with very little loss — handy for long events on one card.' },
  { id: 'b-clock', cam: 'both', cat: 'pair', title: 'Sync the clocks on both bodies',
    body: 'Before a job, set both cameras to the same time, to the second. In Lightroom sort by capture time and the two bodies merge into one story in the right order.' },
  { id: 'b-colour', cam: 'both', cat: 'pair', title: 'Make the two bodies match',
    body: 'Their sensors render colour a little differently. Use the same picture style and a Kelvin white balance on both, shoot one frame of a grey card or colour checker with each body in each lighting setup, then sync the correction across each camera’s photos in the edit.' },
  { id: 'b-roles', cam: 'both', cat: 'pair', title: 'Give each body a job',
    body: 'Put the R8 on the tough jobs: low light, moving people, eye‑AF candids, silent moments and video. Give the 5D II the jobs it does beautifully: well‑lit portraits, flash work, groups, details and a second angle on a tripod. It also carries a wide lens, so you never swap lenses at a key moment.' },
  { id: 'b-sync', cam: 'both', cat: 'flash', title: '1/200 is your flash limit',
    body: 'Both bodies sync at 1/200. Any faster and a dark band appears across the frame, unless the Speedlite is in high‑speed sync (HSS), which costs a lot of power. Outdoors in sun, HSS or an ND filter is how you shoot wide open with fill flash.' },
  { id: 'b-bounce', cam: 'both', cat: 'flash', title: 'Bounce, don’t blast',
    body: 'Point the Speedlite at a white ceiling or at a wall behind or beside you rather than at the subject. The light comes back big and soft. Ceilings above 4 m or dark walls won’t bounce — use the flash’s bounce card or a small diffuser, and add +⅔ to +1 FEC.' },
  { id: 'b-drag', cam: 'both', cat: 'flash', title: 'Drag the shutter on the dance floor',
    body: 'Flash freezes the people; a slow shutter lets the room’s ambient light and colour in. Try M, 1/15–1/30, f/4, ISO 1600–3200, flash on E‑TTL, and set it to second‑curtain sync for light trails behind moving dancers.' },
  { id: 'b-ettl', cam: 'both', cat: 'flash', title: 'E‑TTL works the same on both',
    body: 'Canon EX Speedlites and radio triggers (e.g. the 600EX II‑RT/ST‑E3) run E‑TTL II on both cameras. Flash exposure compensation (FEC) controls the flash and regular exposure comp controls the ambient — in M mode that means shutter/ISO control the background and FEC controls the people.' },
  { id: 'b-sunny16', cam: 'both', cat: 'expo', title: 'The Sunny 16 sanity check',
    body: 'In bright sun: f/16, shutter = 1/ISO (ISO 100 → 1/100). Open up one stop for thin cloud, two for overcast, three for open shade. Handy when the meter is fooled by snow, sand or a white wall.' },
  { id: 'b-dof', cam: 'both', cat: 'expo', title: 'Groups: stop down and step back',
    body: 'For two or more rows of people use at least f/5.6–f/8 and focus on the front‑middle row. The depth of field calculator in Tools shows how deep your focus zone really is at a given distance.' },
  { id: 'b-lowshutter', cam: 'both', cat: 'low', title: 'Low light: aperture first, then ISO',
    body: 'In a dark room open the aperture first (f/1.8–f/2.8), then set the slowest shutter that still freezes people (about 1/125 for moving guests, 1/60 for speeches), and only then raise ISO. A little noise is fine; a blurry face isn’t.' },
  { id: 'b-window', cam: 'both', cat: 'low', title: 'Find the window',
    body: 'Before resorting to flash or high ISO, move people toward a window and face them at 45° to it. Turn off the room’s overhead lights if you can, so mixed colour doesn’t muddy the skin tones.' },
  { id: 'b-format', cam: 'both', cat: 'kit', title: 'The night‑before routine',
    body: 'Charge every battery, format every card in the camera it’ll be used in, clean the lens front elements and sensors, check the date/time, reset exposure comp and ISO, and pack a spare card for each body. The Checklist tab keeps a list you can tick off.' },
  { id: 'b-sensor', cam: 'both', cat: 'kit', title: 'Check for sensor dust',
    body: 'Shoot a plain sky or white wall at f/16 and look for dark spots at 100%. Use a rocket blower with the camera facing down; only wet‑clean if spots won’t move. On the R8 the sensor is exposed when the lens is off, so change lenses quickly with the mount facing down.' },
  { id: 'b-event-candid', cam: 'both', cat: 'event', title: 'Candids: go long and stay back',
    body: 'A 70–200 or 85 mm lets people forget you’re there. Shoot from the edges of the room, wait for interactions (hugs, laughter, reactions to speeches), and point the camera at the listeners during speeches — reactions often beat the speaker.' },
  { id: 'b-group', cam: 'both', cat: 'event', title: 'Group photos without blinks',
    body: 'Shoot 3–5 frames per group, after telling everyone ‘one more’. Get slightly above the group (a chair helps) so faces don’t block each other. Pick the best face from each frame and swap heads in post if needed.' },
  { id: 'b-video-shutter', cam: 'both', cat: 'video', title: 'The 180° shutter rule',
    body: 'For natural motion blur in video, set shutter to double the frame rate: 1/50 for 25p, 1/60 for 30p, 1/125 for 60p. Control brightness with aperture, ISO and an ND filter rather than a faster shutter.' }
];

/* Settings recipes. Each camera column is a starting point, not a rule. */
const RECIPES = [
  { id: 'ceremony', lens: 'R8 + 85 f/1.8 from the back for faces; 5D II + 50 f/1.2L for the room and close moments.', icon: '💍', title: 'Ceremony, no flash',
    when: 'Church, mosque, jamatkhana or hall where flash and shutter noise aren’t welcome.',
    r8:  { Mode: 'M + Auto ISO', Aperture: 'f/2–f/2.8', Shutter: '1/125 (1/250 for movement)', ISO: 'Auto, cap 12,800', Focus: 'Servo, eye detection, whole area', Drive: 'Electronic shutter (silent) — check for LED banding', WB: 'Auto, or measure with a grey card' },
    m2:  { Mode: 'M', Aperture: 'f/2–f/2.8', Shutter: '1/125', ISO: '1600–3200', Focus: 'One Shot, centre point', Drive: 'Silent single (Live View drive) or quiet single', WB: 'Kelvin 3200–4000 under tungsten' },
    notes: 'Put the R8 on a telephoto from the back for faces; the 5D II on a wide lens for the whole room.' },
  { id: 'reception', lens: '5D II + 50 f/1.2L (at f/2.8–f/4) with flash; R8 + RF 50 or 85 for the dance floor.', icon: '🪩', title: 'Reception & dance floor',
    when: 'Dark room, coloured lights, people moving.',
    r8:  { Mode: 'M', Aperture: 'f/4', Shutter: '1/30', ISO: '1600–3200', Focus: 'Servo, eye detection', Drive: 'Elec. 1st‑curtain (flash won’t fire with electronic)', Flash: 'Bounced, E‑TTL, 2nd‑curtain sync', WB: 'Flash / 5500 K' },
    m2:  { Mode: 'M', Aperture: 'f/4', Shutter: '1/30', ISO: '1600', Focus: 'AI Servo, centre point + assist points', Drive: 'Single', Flash: 'Bounced, E‑TTL, 2nd‑curtain sync', WB: 'Flash / 5500 K' },
    notes: 'The 5D II AF struggles in the dark: turn on the Speedlite’s AF‑assist beam, or pre‑focus at a set distance.' },
  { id: 'golden', lens: '85 f/1.8 on the R8 for the classic look; 50 f/1.2L wide open for glow.', icon: '🌅', title: 'Golden‑hour portrait',
    when: 'Low, warm sun an hour before sunset.',
    r8:  { Mode: 'Av', Aperture: 'f/1.8–f/2.8', Shutter: 'Auto (watch it stays under 1/2000 at wide apertures)', ISO: '100–400', Focus: 'Servo, eye detection', Drive: 'Elec. 1st‑curtain', 'Exp. comp': '+⅓ to +1 for backlight', WB: 'Daylight or 5500–6500 K for warmth' },
    m2:  { Mode: 'Av', Aperture: 'f/2–f/2.8', Shutter: 'Auto', ISO: '100–200', Focus: 'One Shot, point on the nearest eye', Drive: 'Single', 'Exp. comp': '+⅔ to +1 for backlight', WB: 'Daylight or 6000 K' },
    notes: 'Put the sun behind them for rim light, and bounce light back into faces with a reflector or white wall.' },
  { id: 'window', lens: '50 f/1.2L at f/1.6–f/2; RF 50 for close details.', icon: '🪟', title: 'Indoor window light',
    when: 'Getting‑ready shots, soft indoor portraits.',
    r8:  { Mode: 'Av', Aperture: 'f/2–f/2.8', Shutter: 'Auto, min 1/125', ISO: 'Auto', Focus: 'One Shot or Servo + eye', Drive: 'Electronic (silent)', WB: 'Daylight; turn room lights off' },
    m2:  { Mode: 'Av', Aperture: 'f/2.8', Shutter: 'Auto (keep ≥ 1/100)', ISO: '400–1600', Focus: 'One Shot, nearest point', Drive: 'Single', WB: 'Daylight' },
    notes: 'Place the person at 45° to the window and expose for the bright side of the face.' },
  { id: 'group', lens: '50 f/1.2L or RF 50 at f/5.6–f/8 — step back rather than go wider.', icon: '👨‍👩‍👧‍👦', title: 'Big group photo',
    when: 'Family formals, team photos, multiple rows.',
    r8:  { Mode: 'M', Aperture: 'f/5.6–f/8', Shutter: '1/160', ISO: 'Auto', Focus: 'One Shot, face detection on the front‑middle row', Drive: 'Elec. 1st‑curtain, bursts of 3', WB: 'Auto or Daylight' },
    m2:  { Mode: 'M', Aperture: 'f/8', Shutter: '1/160', ISO: '400–800', Focus: 'One Shot, centre point on the second row', Drive: 'Continuous, 3–5 frames', WB: 'Daylight' },
    notes: 'Outdoors in sun, put backs to the sun and add fill flash at −1 FEC.' },
  { id: 'headshot', lens: '85 f/1.8 at f/4–f/5.6.', icon: '🧑‍💼', title: 'Business headshot',
    when: 'Staff portraits on a plain background.',
    r8:  { Mode: 'M', Aperture: 'f/4–f/5.6', Shutter: '1/200', ISO: '100', Focus: 'One Shot, eye detection', Drive: 'Elec. 1st‑curtain', Flash: 'Key light at 45° in a softbox', WB: 'Flash / 5500 K' },
    m2:  { Mode: 'M', Aperture: 'f/5.6', Shutter: '1/200', ISO: '100', Focus: 'One Shot, point on the nearest eye', Drive: 'Single', Flash: 'Key light at 45° in a softbox', WB: 'Flash / 5500 K' },
    notes: '85–135 mm flatters faces. Keep them 1–2 m from the backdrop so it stays clean. Tethered, the client can pick shots on the spot.' },
  { id: 'product', lens: 'RF 50 f/1.8 on the R8 (30 cm close focus) for small items; 85 for tighter framing without distortion.', icon: '🏭', title: 'Products & factory',
    when: 'Commercial work: products on a table, machinery, facilities.',
    r8:  { Mode: 'M on a tripod', Aperture: 'f/8–f/11', Shutter: 'Whatever exposes (tripod)', ISO: '100', Focus: 'Manual with magnify, or focus bracketing', Drive: '2‑s timer, electronic shutter', WB: 'Custom from a grey card' },
    m2:  { Mode: 'M on a tripod', Aperture: 'f/8–f/11', Shutter: 'Whatever exposes (tripod)', ISO: '100', Focus: 'Live View 10× manual', Drive: '2‑s timer + mirror lockup', WB: 'Custom from a grey card' },
    notes: 'In factories, fluorescent and LED lights flicker: keep the shutter at 1/50 or slower (or 1/60 in 60 Hz countries, e.g. Canada) to avoid colour shifts between frames.' },
  { id: 'action', lens: 'R8 + 85 f/1.8 (fast USM and subject tracking).', icon: '⚽', title: 'Sports, kids & pets',
    when: 'Fast, unpredictable movement.',
    r8:  { Mode: 'Tv or M + Auto ISO', Aperture: 'f/2.8–f/4', Shutter: '1/1000 (1/500 for walking)', ISO: 'Auto', Focus: 'Servo, subject detection (people or animals)', Drive: 'High‑speed continuous', WB: 'Auto' },
    m2:  { Mode: 'Tv', Aperture: 'Auto', Shutter: '1/1000', ISO: '400–1600', Focus: 'AI Servo, centre + assist points', Drive: 'Continuous (3.9 fps)', WB: 'Auto' },
    notes: 'Use the R8 for this if you can — its tracking and frame rate are generations ahead.' },
  { id: 'landscape', lens: '50 f/1.2L or RF 50 at f/8; stitch a panorama if you need wider.', icon: '🏔️', title: 'Landscape',
    when: 'Scenery, cityscapes, architecture.',
    r8:  { Mode: 'Av or M on a tripod', Aperture: 'f/8–f/11', Shutter: 'Auto', ISO: '100', Focus: 'Manual at the hyperfocal distance (see Tools)', Drive: '2‑s timer, AEB ±2 for high contrast', WB: 'Daylight' },
    m2:  { Mode: 'Av or M on a tripod', Aperture: 'f/8–f/11', Shutter: 'Auto', ISO: '100', Focus: 'Live View 10×, a third into the scene', Drive: '2‑s timer + mirror lockup, AEB ±2', WB: 'Daylight' },
    notes: 'Past f/11, diffraction starts to soften both sensors. Use a polariser for skies and water.' },
  { id: 'astro', lens: 'Your lenses are all 50 mm or longer, so exposures must be short (≈ 4–5 s for pin‑sharp stars at 50 mm). A wide lens, 14–24 mm, makes this far easier.', icon: '🌌', title: 'Night sky & Milky Way',
    when: 'Dark site, no moon, clear sky.',
    r8:  { Mode: 'M on a tripod', Aperture: 'Widest (f/1.4–f/2.8)', Shutter: 'See the star‑trail calculator (≈15–20 s at 20 mm)', ISO: '3200–6400', Focus: 'Manual on a bright star, magnified', Drive: '2‑s or 10‑s timer', WB: '3800–4200 K' },
    m2:  { Mode: 'M on a tripod', Aperture: 'Widest (f/1.4–f/2.8)', Shutter: 'See the star‑trail calculator', ISO: '1600–3200', Focus: 'Live View 10× on a bright star', Drive: '2‑s timer + mirror lockup', WB: '3800–4200 K' },
    notes: 'Turn off Long exposure noise reduction if you’re shooting a sequence to stack. The R8 is much cleaner at high ISO — give it the job.' },
  { id: 'booth', lens: 'RF 50 f/1.8 on the R8 at f/5.6–f/8.', icon: '📸', title: 'Photo booth',
    when: 'Tethered booth at an event.',
    r8:  { Mode: 'M', Aperture: 'f/5.6–f/8', Shutter: '1/125–1/200', ISO: '200–400', Focus: 'One Shot, face detection (or manual at a fixed distance)', Drive: 'Elec. 1st‑curtain (flash) — never full electronic', Power: 'USB‑PD or DR‑E17 coupler, Auto power off: Disable', WB: 'Flash / 5500 K' },
    m2:  { Mode: 'M', Aperture: 'f/8', Shutter: '1/125', ISO: '200', Focus: 'Manual, pre‑set to the standing mark', Drive: 'Single', Power: 'ACK‑E6 AC adapter', WB: 'Flash / 5500 K' },
    notes: 'f/8 keeps a group of four at different depths all sharp. Tape a mark on the floor so guests stand where focus is.' },
  { id: 'interview', lens: 'R8 + 85 for the close‑up; 5D II + 50 f/1.2L for the medium shot.', icon: '🎙️', title: 'Video interview',
    when: 'Sit‑down talking‑head video.',
    r8:  { Mode: 'Video, manual exposure', Aperture: 'f/2.8–f/4', Shutter: '1/50 (25p) or 1/60 (30p)', ISO: 'As low as the light allows', Focus: 'Movie Servo AF, eye detection', Format: '4K 25/30p, normal picture style', Audio: 'External mic, manual levels, peaks −12 dB' },
    m2:  { Mode: 'Movie, manual exposure', Aperture: 'f/2.8–f/4', Shutter: '1/50 (25p) or 1/60 (30p)', ISO: 'As low as the light allows', Focus: 'Manual — set it and keep the subject seated', Format: '1080p 25/30p, Neutral picture style', Audio: 'Separate recorder; clips stop at 4 GB' },
    notes: 'Use both at once: R8 on a medium shot, 5D II on a tighter or side angle. Clap once at the start of each take to sync the clips.' }
];

const CHECKLIST = [
  { g: 'Night before', items: [
    'Charge every battery (R8 LP‑E17 × 3+, 5D II LP‑E6 × 2)',
    'Format cards in the camera they’ll go in',
    'Sync the clock on both cameras',
    'Reset exposure comp, ISO and drive mode',
    'Clean front elements; blower on sensors',
    'Test Speedlites + triggers, pack spare AAs',
    'Pack the EF‑EOS R adapter + rear caps for every lens'
  ]},
  { g: 'On arrival', items: [
    'Walk the venue and find windows and bounce surfaces',
    'Check the lights for flicker/banding with a test shot',
    'Grey card / colour checker frame on each body',
    'Set white balance for the main room',
    'R8 shutter mode matches the plan (1st‑curtain for flash)'
  ]},
  { g: 'After the job', items: [
    'Back up cards to two places before formatting',
    'Charge batteries and store them half‑full if unused for a while',
    'Wipe down bodies and lenses',
    'Note anything that went wrong in this app’s Notes'
  ]}
];
